name: CI
on:
  push:
    branches:
      - '*'
      - '*/*'
      - '**'
      - '!main'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - name: Install deps
        run: npm ci
      - name: Lint affected
        run: npx nx affected -t lint
      - name: Test affected
        run: npx nx affected -t test --configuration=ci
      - name: Build affected
        run: npx nx affected -t build

      - name: Check if package exists
        id: check_package_exists
        run: |
          if npm show @mononxtest/hoho > /dev/null 2>&1; then
            echo "PACKAGE_EXISTS=true" >> $GITHUB_ENV
          else
            echo "PACKAGE_EXISTS=false" >> $GITHUB_ENV
          fi

      - name: Extract Latest Version
        id: extract_latest_version
        run: |
          if [ "${{ env.PACKAGE_EXISTS }}" == "true" ]; then
            echo "LATEST_VERSION=$(npm show @mononxtest/hoho version)" >> $GITHUB_ENV
          fi
      - run: echo ${{ env.PACKAGE_EXISTS }}
