name: pre-release

on:
  push:
    branches:
      - 'rc/*'

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      affected: ${{ steps.set-output.outputs.affected }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3

      - run: npm ci

      - name: Identify affected projects
        run: |
          echo "AFFECTED=$(npx nx show projects --affected --json | jq -r '. | join(" ")')" >> $GITHUB_ENV

      - name: Set affected projects as output
        id: set-output
        run: echo "::set-output name=affected::${{ env.AFFECTED }}"

#      - run: npx nx affected -t lint
#
#      - run: npx nx affected -t semantic-release
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}