name: RELEASE
on: [workflow_dispatch]
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - name: Install deps
        run: npm ci
      - name: Lint
        run: npx nx run-many -t lint
      - name: Test
        run: npx nx run-many -t test --configuration=ci
      - name: Release
        run: npx semantic-release
        id: dry-run-release-version
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    outputs:
      new-release-published: ${{ steps.dry-run-release-version.outputs.new-release-published }}
      new-release-version: ${{ steps.dry-run-release-version.outputs.new-release-version }}

  tt:
    runs-on: ubuntu-latest
    needs: main
    steps:
      - uses: actions/checkout@v3
      - run: echo "The new release version is ${{ needs.get-next-version.outputs.new-release-version }}"
